# Generated by Django 4.2.2 on 2024-04-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sent_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
